USE db_car_rental_solutis;

INSERT INTO tb_fabricante (nome)
VALUES ('Toyota'),
       ('Honda'),
       ('Hyundai'),
       ('Jeep'),
       ('Volkswagen'),
       ('Ford'),
       ('Chevrolet'),
       ('Nissan'),
       ('Kia'),
       ('Mazda'),
       ('Subaru'),
       ('BMW'),
       ('Mercedes-Benz'),
       ('Audi'),
       ('Volkswagen'),
       ('Peugeot'),
       ('Renault'),
       ('Fiat'),
       ('Land Rover'),
       ('Porsche'),
       ('Mitsubishi'),
       ('Chrysler'),
       ('Buick'),
       ('GMC'),
       ('Cadillac'),
       ('Jaguar'),
       ('Lexus'),
       ('Infiniti'),
       ('Acura'),
       ('Alfa Romeo'),
       ('Tesla'),
       ('Rover'),
       ('Mini'),
       ('Lincoln'),
       ('Saturn'),
       ('Saab'),
       ('Dodge'),
       ('Mazda'),
       ('Opel'),
       ('Seat'),
       ('Skoda');
