USE db_car_rental_solutis;

INSERT INTO tb_modelo_carro (descricao, fabricante_id, categoria)
VALUES ('Corolla', 1, 'SEDAN_COMPACTO'),
       ('Civic', 2, 'SEDAN_MEDIO'),
       ('Elantra', 3, 'SEDAN_MEDIO'),
       ('Compass', 4, 'UTILITARIO_COMERCIAL'),
       ('Golf', 5, 'HATCH_MEDIO'),
       ('Mustang', 6, 'ESPORTIVO'),
       ('Cruze', 7, 'SEDAN_MEDIO'),
       ('Altima', 8, 'SEDAN_GRANDE'),
       ('Soul', 9, 'UTILITARIO_COMERCIAL'),
       ('MX-5 Miata', 10, 'ESPORTIVO'),
       ('Outback', 11, 'UTILITARIO_COMERCIAL'),
       ('X3', 12, 'UTILITARIO_COMERCIAL'),
       ('C-Class', 13, 'SEDAN_MEDIO'),
       ('A4', 14, 'SEDAN_MEDIO'),
       ('308', 15, 'HATCH_MEDIO'),
       ('Clio', 16, 'HATCH_COMPACTO'),
       ('Punto', 17, 'HATCH_COMPACTO'),
       ('Range Rover', 18, 'UTILITARIO_COMERCIAL'),
       ('911', 19, 'ESPORTIVO'),
       ('Outlander', 20, 'UTILITARIO_COMERCIAL'),
       ('300C', 21, 'SEDAN_GRANDE'),
       ('Enclave', 22, 'UTILITARIO_COMERCIAL'),
       ('Yukon', 23, 'UTILITARIO_COMERCIAL'),
       ('XT5', 24, 'UTILITARIO_COMERCIAL'),
       ('F-Pace', 25, 'UTILITARIO_COMERCIAL'),
       ('RX', 26, 'UTILITARIO_COMERCIAL'),
       ('Q7', 27, 'UTILITARIO_COMERCIAL'),
       ('Giulia', 28, 'SEDAN_MEDIO'),
       ('Model 3', 29, 'SEDAN_COMPACTO'),
       ('Freelander', 30, 'UTILITARIO_COMERCIAL'),
       ('Clubman', 31, 'MINIVAN'),
       ('Navigator', 32, 'UTILITARIO_COMERCIAL'),
       ('Astra', 33, 'HATCH_MEDIO'),
       ('Ibiza', 34, 'HATCH_COMPACTO'),
       ('Octavia', 35, 'SEDAN_MEDIO');

SELECT * FROM tb_modelo_carro;